import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CommentProvider } from "context/commentContext";
import { PostProvider } from "context/postsContext";
import Navbar from "@components/Navbar";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <>
          <PostProvider>
            <CommentProvider>
              <Navbar />
              {children}
            </CommentProvider>
          </PostProvider>
        </>
      </body>
    </html>
  );
}
